### PR TITLE
Fix libs install errors on clean mac/linux envs

### PR DESCRIPTION
**Pull request by agur**

### CODE REVIEW

**Review by chjch — APPROVED** [review]

**Review by chjch — CHANGES_REQUESTED** [review]
@agur Seems like the latest geopandas version is 0.11.0 [https://geopandas.org/en/stable/docs/changelog.html](https://geopandas.org/en/stable/docs/changelog.html)

**Comment by agur** [comment]
> @agur Seems like the latest geopandas version is 0.11.0 https://geopandas.org/en/stable/docs/changelog.html

Thanks.
It was not missing and worked on the envs I listed w/ newer python and the committed code.  (at least running pytest worked)
See: https://pypi.org/project/geopandas/#history, apparently 0.11.1 was published, but they have not updated the docs.

Specifically:
python 3.6 can work up to geopandas 0.9.0
python 3.7 can work up to geopandas 0.10.2

Saw you added python 3.8 - 3.10, can be handy to work on all.  We can check it.  If one lib combination works on all it could be worth the support.  Will check.

**Comment by chjch** [comment]
@agur still getting errors for the workflow `tests_pylusat.yml`. Seems like it only supports `geopands` until version 0.9.0. Run result is here:
https://github.com/chjch/pylusat/actions/runs/3129300508/jobs/5078217933#step:4:37

**Comment by agur** [comment]
Hi @chjch - even on a clean 3.6.15 - it still fails on the original set of libs in requirements.txt.
I am trying to work on clean envs on each version and solve it for all, will update/commit as I progress.

**Comment by agur** [comment]
> @agur still getting errors for the workflow `tests_pylusat.yml`. Seems like it only supports `geopands` until version 0.9.0. Run result is here: https://github.com/chjch/pylusat/actions/runs/3129300508/jobs/5078217933#step:4:37

Yes, saw that and mentioned 3.6 can max use 0.9.0 (see [here](https://github.com/chjch/pylusat/pull/4#issuecomment-1257660529)).  Working on trying to have them all work.

**Pull request merged**
